# Generated by Django 2.0.4 on 2018-05-15 09:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyMusic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2005, 7, 27))),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('casi', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=300)),
                ('nguoimua', models.ManyToManyField(through='home.BuyMusic', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='buymusic',
            name='music',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Music'),
        ),
        migrations.AddField(
            model_name='buymusic',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
